#!/bin/bash
# add-to-compose.sh - Add a tenant to docker-compose.yml
# Usage: ./add-to-compose.sh <tenant-name> <port>

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="${SCRIPT_DIR}/docker-compose.yml"
DATA_DIR="/data"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

print_success() { echo -e "${GREEN}✓${NC} $1"; }
print_warning() { echo -e "${YELLOW}!${NC} $1"; }
print_error() { echo -e "${RED}✗${NC} $1"; }

TENANT_NAME="${1:-}"
PORT="${2:-}"

if [[ -z "$TENANT_NAME" ]] || [[ -z "$PORT" ]]; then
    echo "Usage: $0 <tenant-name> <port>"
    echo ""
    echo "Example: $0 my-tenant 18790"
    exit 1
fi

# Verify tenant directory exists
TENANT_DIR="${DATA_DIR}/${TENANT_NAME}"
if [[ ! -d "$TENANT_DIR" ]]; then
    print_error "Tenant directory not found: $TENANT_DIR"
    echo "Run provision-tenant.sh first"
    exit 1
fi

# Check if compose file exists
if [[ ! -f "$COMPOSE_FILE" ]]; then
    print_error "docker-compose.yml not found"
    echo "Creating new docker-compose.yml..."

    cat > "$COMPOSE_FILE" << 'HEADER'
# OpenClaw Multi-Tenant Docker Compose
# Generated by add-to-compose.sh

version: '3.8'

x-common-settings: &common-settings
  image: openclaw:2026.2.3
  restart: always
  network_mode: bridge
  cap_drop:
    - ALL
  cap_add:
    - NET_BIND_SERVICE
  security_opt:
    - no-new-privileges:true
  deploy:
    resources:
      limits:
        cpus: '2.0'
        memory: 2G
      reservations:
        cpus: '0.5'
        memory: 512M

services:
HEADER
    print_success "Created docker-compose.yml"
fi

# Check if tenant already exists in compose
if grep -q "openclaw-${TENANT_NAME}:" "$COMPOSE_FILE" 2>/dev/null; then
    print_warning "Tenant '${TENANT_NAME}' already exists in docker-compose.yml"
    exit 0
fi

# Generate service entry
SERVICE_ENTRY=$(cat << EOF

  ${TENANT_NAME}:
    <<: *common-settings
    container_name: openclaw-${TENANT_NAME}
    env_file:
      - ${TENANT_DIR}/secrets.env
    environment:
      - CLAWDBOT_GATEWAY_PORT=18789
    volumes:
      - ${TENANT_DIR}/.openclaw:/root/.openclaw
      - /data/shared/skills:/root/clawd/skills:ro
      - /data/shared/plugins:/root/clawd/plugins:ro
    ports:
      - "${PORT}:18789"
EOF
)

# Append to docker-compose.yml
echo "$SERVICE_ENTRY" >> "$COMPOSE_FILE"

print_success "Added tenant '${TENANT_NAME}' to docker-compose.yml"
echo ""
echo "Start with: docker compose up -d ${TENANT_NAME}"
